/** Emoji for group icons.
 *
 * A curated set rather than a picker library: every one I looked at either
 * fetches its data or its images from a CDN, and this app has to work on a
 * laptop with no network and inside iTerm2's browser. A few hundred icons is
 * more than enough to label a group, costs a couple of kilobytes, and renders
 * as plain text - nothing to load, nothing to block.
 *
 * Each entry is [emoji, keywords]. The keywords are what search matches on, so
 * "db" finds the filing cabinet and "prod" finds the rocket.
 */

export interface EmojiCategory {
  id: string
  label: string
  emoji: [string, string][]
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'infra',
    label: 'Infra',
    emoji: [
      ['🚀', 'rocket launch prod production deploy ship fast'],
      ['🖥️', 'desktop computer server machine host'],
      ['💻', 'laptop computer dev develop machine'],
      ['🗄️', 'file cabinet database db storage archive'],
      ['🗃️', 'card box database db records storage'],
      ['💾', 'floppy disk save storage backup'],
      ['💿', 'disc cd storage'],
      ['📦', 'package box build artifact release container'],
      ['🐳', 'whale docker container'],
      ['☁️', 'cloud aws gcp azure hosting'],
      ['🌐', 'globe web network internet www'],
      ['📡', 'satellite dish network signal monitoring'],
      ['🛰️', 'satellite space network remote'],
      ['🔌', 'plug power socket connect'],
      ['⚙️', 'gear settings config system service'],
      ['🛠️', 'tools build maintenance ops'],
      ['🔧', 'wrench fix tools ops maintenance'],
      ['🧰', 'toolbox tools utilities kit'],
      ['🧪', 'test tube staging experiment qa lab'],
      ['🔬', 'microscope research analysis lab'],
      ['🧱', 'brick wall infrastructure foundation'],
      ['🏗️', 'construction building work in progress'],
      ['🏭', 'factory production plant industrial'],
      ['🏢', 'office building company corporate'],
      ['🏦', 'bank finance payments money'],
      ['🖨️', 'printer output device'],
      ['⌨️', 'keyboard input terminal'],
      ['🖱️', 'mouse input device'],
      ['📟', 'pager alert oncall'],
      ['📠', 'fax legacy old'],
      ['🧮', 'abacus compute calculation'],
      ['📊', 'bar chart metrics analytics dashboard'],
      ['📈', 'chart up growth metrics trending'],
      ['📉', 'chart down metrics decline'],
      ['🗂️', 'dividers folders organize index'],
      ['📁', 'folder directory files group'],
      ['📂', 'open folder directory files'],
      ['🔍', 'magnifier search find lookup'],
      ['🔒', 'lock secure private locked'],
      ['🔓', 'unlock open access'],
      ['🔑', 'key access credential auth login'],
      ['🛡️', 'shield security protection firewall'],
      ['🧯', 'extinguisher incident firefighting oncall'],
      ['🚨', 'siren alert incident emergency oncall'],
      ['⏱️', 'stopwatch timing performance latency'],
    ],
  },
  {
    id: 'symbols',
    label: 'Symbols',
    emoji: [
      ['✅', 'check tick done ok pass green'],
      ['❌', 'cross fail error no red'],
      ['⚠️', 'warning caution alert careful'],
      ['❗', 'exclamation important urgent'],
      ['❓', 'question unknown help'],
      ['💡', 'idea lightbulb tip insight'],
      ['✨', 'sparkles new shiny feature'],
      ['🔥', 'fire hot urgent burning critical'],
      ['⚡', 'lightning fast power energy zap'],
      ['💥', 'boom crash explosion incident'],
      ['🎯', 'target goal objective focus'],
      ['🏁', 'finish flag done complete race'],
      ['🚩', 'flag marker attention milestone'],
      ['📌', 'pin pinned important fixed'],
      ['📎', 'paperclip attach link'],
      ['🔗', 'link chain url connection'],
      ['🔔', 'bell notification alert'],
      ['♻️', 'recycle refresh reuse rotate'],
      ['🆕', 'new fresh recent'],
      ['🆗', 'ok fine approved'],
      ['🔝', 'top priority high up'],
      ['🔴', 'red circle critical prod stop'],
      ['🟠', 'orange circle warning'],
      ['🟡', 'yellow circle caution'],
      ['🟢', 'green circle healthy ok go'],
      ['🔵', 'blue circle info'],
      ['🟣', 'purple circle'],
      ['⚫', 'black circle dark off'],
      ['⚪', 'white circle light neutral'],
      ['🟤', 'brown circle'],
      ['♾️', 'infinity endless always'],
      ['🔱', 'trident three prongs'],
    ],
  },
  {
    id: 'places',
    label: 'Places',
    emoji: [
      ['🌍', 'earth globe europe africa world region'],
      ['🌎', 'earth globe americas world region us'],
      ['🌏', 'earth globe asia australia world region apac'],
      ['🗺️', 'map world region location'],
      ['🏠', 'house home local personal'],
      ['🏡', 'house garden home local'],
      ['🏰', 'castle fortress legacy'],
      ['🗼', 'tower landmark tokyo'],
      ['🗽', 'liberty statue us new york'],
      ['⛰️', 'mountain peak high'],
      ['🏔️', 'snow mountain peak alps'],
      ['🏝️', 'island isolated remote sandbox'],
      ['🏖️', 'beach holiday relaxed sandbox'],
      ['🌋', 'volcano eruption risky unstable'],
      ['🚗', 'car drive transport'],
      ['🚚', 'truck delivery transport logistics'],
      ['✈️', 'plane flight travel deploy'],
      ['🚢', 'ship shipping deploy release'],
      ['⛵', 'sailboat sailing slow'],
      ['🛸', 'ufo experimental alien future'],
      ['🚦', 'traffic light gating rollout'],
      ['🛰️', 'satellite orbit remote'],
    ],
  },
  {
    id: 'nature',
    label: 'Nature',
    emoji: [
      ['🌱', 'seedling new growth sprout dev'],
      ['🌲', 'tree evergreen forest'],
      ['🌳', 'tree green forest'],
      ['🌴', 'palm tree holiday tropical'],
      ['🌵', 'cactus desert dry standalone'],
      ['🍀', 'clover luck fortune'],
      ['🌻', 'sunflower bright happy'],
      ['🌸', 'blossom flower spring pink'],
      ['🌊', 'wave water ocean flow stream'],
      ['❄️', 'snowflake cold frozen freeze'],
      ['☀️', 'sun day bright clear'],
      ['🌙', 'moon night nightly batch'],
      ['⭐', 'star favourite important'],
      ['🌟', 'glowing star special highlight'],
      ['🌈', 'rainbow colourful variety'],
      ['🐶', 'dog puppy pet'],
      ['🐱', 'cat kitten pet'],
      ['🦊', 'fox firefox clever'],
      ['🐼', 'panda cute'],
      ['🐧', 'penguin linux'],
      ['🦉', 'owl night wise monitoring'],
      ['🐝', 'bee busy worker swarm'],
      ['🐢', 'turtle slow steady'],
      ['🐇', 'rabbit fast quick'],
      ['🐙', 'octopus git github tentacles'],
      ['🐬', 'dolphin mysql smart'],
      ['🦈', 'shark dangerous fast'],
      ['🦋', 'butterfly change transform'],
    ],
  },
  {
    id: 'people',
    label: 'People',
    emoji: [
      ['👤', 'person user account single'],
      ['👥', 'people users team group shared'],
      ['🧑‍💻', 'developer engineer coding technologist'],
      ['👨‍💻', 'developer engineer coding man'],
      ['👩‍💻', 'developer engineer coding woman'],
      ['🧑‍🔧', 'mechanic ops engineer maintenance'],
      ['🧑‍🚀', 'astronaut space launch'],
      ['🕵️', 'detective investigation debugging audit'],
      ['🧙', 'wizard magic advanced'],
      ['🦸', 'hero superhero critical'],
      ['🤖', 'robot bot automation ci agent'],
      ['👻', 'ghost hidden legacy haunted'],
      ['💀', 'skull dead deprecated danger'],
      ['🎃', 'pumpkin halloween seasonal'],
      ['🧟', 'zombie legacy undead'],
      ['🧑‍🏫', 'teacher training demo'],
      ['🤝', 'handshake partner shared client'],
      ['👋', 'wave hello onboarding intro'],
    ],
  },
  {
    id: 'things',
    label: 'Things',
    emoji: [
      ['☕', 'coffee break morning caffeine'],
      ['🍵', 'tea calm break'],
      ['🍺', 'beer friday celebration'],
      ['🍕', 'pizza food fun'],
      ['🍔', 'burger food fun'],
      ['🌮', 'taco food fun'],
      ['🍩', 'donut food sweet'],
      ['🍪', 'cookie session cache sweet'],
      ['🎉', 'party celebration launch release'],
      ['🎊', 'confetti celebration launch'],
      ['🎁', 'gift present bonus'],
      ['🎈', 'balloon light fun'],
      ['🏆', 'trophy winner best primary'],
      ['🥇', 'gold medal first primary'],
      ['🎮', 'game controller play fun'],
      ['🎲', 'dice random chance'],
      ['🎧', 'headphones audio focus'],
      ['🎵', 'music note audio'],
      ['📚', 'books docs knowledge library'],
      ['📖', 'book docs reading manual'],
      ['📝', 'memo notes writing todo'],
      ['📅', 'calendar schedule cron daily'],
      ['⏰', 'alarm clock schedule cron'],
      ['💰', 'money bag billing finance revenue'],
      ['💳', 'credit card payments billing'],
      ['🛒', 'cart shop ecommerce orders'],
      ['📮', 'postbox mail queue messages'],
      ['✉️', 'envelope mail email smtp'],
      ['📬', 'mailbox inbox messages queue'],
      ['🔋', 'battery power capacity'],
      ['🧲', 'magnet attract pull sync'],
      ['🪝', 'hook webhook integration'],
    ],
  },
]

/** Every emoji, flattened - used by search. */
const ALL: [string, string][] = EMOJI_CATEGORIES.flatMap((c) => c.emoji)

export function searchEmoji(term: string): [string, string][] {
  const query = term.trim().toLowerCase()
  if (!query) return []
  const words = query.split(/\s+/)
  return ALL.filter(([emoji, keywords]) =>
    words.every((word) => keywords.includes(word) || emoji === word),
  )
}
